#StatusBox配置文件
#Design By MossCG

#前言
#当你确认配置没问题后，请将以下选项修改为true后再启动客户端喵
enable: false

#运行模式
#CLIENT/SERVER，对应客户端/服务端
#务必全部大写喵，乱填默认CLIENT喵
runMode: "CLIENT"

#----------------------------------
#客户端设置

#服务端API地址
#前面的“http://”协议头和后面的”/API“别漏了
#示例："http://127.0.0.1:4698/?API"
APIAddress: "http://127.0.0.1:4698/API"

#该节点的编号
nodeID: "test"
#该节点的密码
nodeAuth: "1234567890"

#----------------------------------
#服务端设置

#HttpAPI服务端口
httpPort: 4698

#HttpAPI线程池大小
#线程池越大，并发性能越好，性能占用越多
#一般10够用，多了没必要
httpPoolSize: 10
#HttpAPI最大每秒请求数
#当QPS超过此阈值时，会有警告信息
#推荐200
httpMaxQPS: 200

#----------------------------------
#是否显示调试信息
debug: false
